### ISSUE TITLE
Please add a description and a README for this repo

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-icao-transliteration#1]
Title says it all, I think :D

**Comment by Ein-Tim** [comment]
@dsarkar Could you push this issue a bit, please, so that we can merge https://github.com/corona-warn-app/cwa-documentation/pull/876?

**Comment by dsarkar** [comment]
@Ein-Tim I will try to get some info.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-12907](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12907)

**Comment by Ein-Tim** [comment]
@dsarkar Any update here?

**Comment by dsarkar** [comment]
@Ein-Tim not yet, I will ask again.

**Comment by dsarkar** [comment]
Hi @daniel-eder @ggrund-tsi,

similarly to the other repositories in this project, would you provide a readme and description for this repository?

Many thanks! Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by daniel-eder** [comment]
@dsarkar Thanks for the ping, I'll talk to @ggrund-tsi about the exact purpose of this repo and we'll set up a readme

**Comment by daniel-eder** [comment]
Closed in #1c25ad9a57e019f0775361f6d3243eb804f6b8c3

@Ein-Tim thanks for the hint and @dsarkar as always thank you for your support
